src/main/java/itakademija/java2015/myapp/entities/Client.java
package itakademija.java2015.myapp.entities;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;

@Entity
public class Client {

    @Id
    @GeneratedValue
    private Long id;

    private String name;
    
    private String surname;
    
    private String city;

    private String phone;

    @OneToMany(mappedBy = "client", orphanRemoval = true, fetch = FetchType.EAGER)
    private List<Survey> surveys;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((surname == null) ? 0 : surname.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof Client)) {
            return false;
        }
        Client other = (Client) obj;
        if (surname == null) {
            if (other.surname != null) {
                return false;
            }
        } else if (!surname.equals(other.surname)) {
            return false;
        }
        if (id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!id.equals(other.id)) {
            return false;
        }
        return true;
    }

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public List<Survey> getSurveys() {
		return surveys;
	}

	public void setSurveys(List<Survey> surveys) {
		this.surveys = surveys;
	}
    
    
}

src/main/java/itakademija/java2015/myapp/entities/Survey.java
package itakademija.java2015.myapp.entities;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Survey {

    @Id
    @GeneratedValue
    private Long id;
    
    @Temporal(TemporalType.DATE)
    private Date surveyDate;
    
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "client_id")
    private Client client;
    
    private int satisfaction;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return ("survey id: " + id);
    }

	public Date getSurveyDate() {
		return surveyDate;
	}

	public void setSurveyDate(Date surveyDate) {
		this.surveyDate = surveyDate;
	}

	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public int getSatisfaction() {
		return satisfaction;
	}

	public void setSatisfaction(int satisfaction) {
		this.satisfaction = satisfaction;
	}

}

src/main/java/itakademija/java2015/myapp/entities/repositories/ClientRepository.java
package itakademija.java2015.myapp.entities.repositories;

import itakademija.java2015.myapp.entities.Client;

import java.util.List;

public interface ClientRepository {

    void save(Client newClient);

    void delete(Client client);

    List<Client> findAll();

    Client findById(Long id);

    Long countClients();

}

src/main/java/itakademija/java2015/myapp/entities/repositories/SurveyRepository.java
package itakademija.java2015.myapp.entities.repositories;

import itakademija.java2015.myapp.entities.Client;
import itakademija.java2015.myapp.entities.Survey;

import java.util.List;

public interface SurveyRepository {

    public void save(Survey survey);

    public void delete(Survey survey);

    public List<Survey> findAll();

    public List<Survey> findAllByClient(Client client);

}

src/main/java/itakademija/java2015/myapp/entities/repositories/jpa/ClientRepositoryJPA.java
package itakademija.java2015.myapp.entities.repositories.jpa;

import itakademija.java2015.myapp.entities.Client;
import itakademija.java2015.myapp.entities.repositories.ClientRepository;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ClientRepositoryJPA implements ClientRepository {

    static final Logger log = LoggerFactory.getLogger(ClientRepositoryJPA.class);

    public void init() {
        log.warn("Bean created");
    }

    public void destroy() {
        log.warn("Bean destroyed");
    }

    private EntityManagerFactory entityManagerFactory;

    public void setEntityManagerFactory(EntityManagerFactory emf) {
        this.entityManagerFactory = emf;
    }

    private EntityManager getEntityManager() {
        return entityManagerFactory.createEntityManager();
    }

    @Override
    public void save(Client client) {
        EntityManager entityManager = getEntityManager();
        try {
            entityManager.getTransaction().begin();
            if (!entityManager.contains(client))
                client = entityManager.merge(client);
            entityManager.persist(client);
            entityManager.getTransaction().commit();
        } finally {
            entityManager.close();
        }

    }

    @Override
    public void delete(Client client) {
        EntityManager entityManager = getEntityManager();
        try {
            entityManager.getTransaction().begin();
            client = entityManager.merge(client);
            entityManager.remove(client);
            entityManager.getTransaction().commit();
        } finally {
            entityManager.close();
        }

    }

    @Override
    public List<Client> findAll() {
        EntityManager entityManager = getEntityManager();
        try {
            CriteriaBuilder cb = entityManager.getCriteriaBuilder();
            CriteriaQuery<Client> cq = cb.createQuery(Client.class);
            Root<Client> root = cq.from(Client.class);
            cq.select(root);
            TypedQuery<Client> q = entityManager.createQuery(cq);
            return q.getResultList();
        } finally {
            entityManager.close();
        }
    }

    @Override
    public Long countClients() {
        EntityManager entityManager = getEntityManager();
        try {
            CriteriaBuilder cb = entityManager.getCriteriaBuilder();
            CriteriaQuery<Long> cq = cb.createQuery(Long.class);
            Root<Client> root = cq.from(Client.class);
            cq.select(cb.count(root));
            TypedQuery<Long> q = entityManager.createQuery(cq);
            return q.getSingleResult();
        } finally {
            entityManager.close();
        }
    }

    @Override
    public Client findById(Long id) {
        EntityManager entityManager = getEntityManager();
        try {
            CriteriaBuilder cb = entityManager.getCriteriaBuilder();
            CriteriaQuery<Client> cq = cb.createQuery(Client.class);
            Root<Client> root = cq.from(Client.class);
            cq.where(cb.equal(root.get("id"), id));
            TypedQuery<Client> q = entityManager.createQuery(cq);
            return q.getSingleResult();
        } finally {
            entityManager.close();
        }
    }

}

src/main/java/itakademija/java2015/myapp/entities/repositories/jpa/SurveyRepositoryJPA.java
package itakademija.java2015.myapp.entities.repositories.jpa;

import itakademija.java2015.myapp.entities.Client;
import itakademija.java2015.myapp.entities.Survey;
import itakademija.java2015.myapp.entities.repositories.SurveyRepository;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SurveyRepositoryJPA implements SurveyRepository {

    static final Logger log = LoggerFactory.getLogger(ClientRepositoryJPA.class);

    public void init() {
        log.warn("Bean created");
    }

    public void destroy() {
        log.warn("Bean destroyed");
    }

    private EntityManagerFactory entityManagerFactory;

    public void setEntityManagerFactory(EntityManagerFactory emf) {
        this.entityManagerFactory = emf;
    }

    private EntityManager getEntityManager() {
        return entityManagerFactory.createEntityManager();
    }

    @Override
    public void save(Survey survey) {
        EntityManager entityManager = getEntityManager();
        try {
            entityManager.getTransaction().begin();
            if (!entityManager.contains(survey) && survey.getId() != null) {
                survey = entityManager.merge(survey);
            }
            entityManager.persist(survey);
            entityManager.getTransaction().commit();
        } finally {
            entityManager.close();
        }

    }

    @Override
    public void delete(Survey survey) {
        EntityManager entityManager = getEntityManager();
        try {
            entityManager.getTransaction().begin();
            survey = entityManager.merge(survey);
            entityManager.remove(survey);
            entityManager.getTransaction().commit();
        } finally {
            entityManager.close();
        }
    }

    @Override
    public List<Survey> findAll() {
        EntityManager entityManager = getEntityManager();
        try {
            CriteriaBuilder cb = entityManager.getCriteriaBuilder();
            CriteriaQuery<Survey> cq = cb.createQuery(Survey.class);
            Root<Survey> root = cq.from(Survey.class);
            cq.select(root);
            TypedQuery<Survey> q = entityManager.createQuery(cq);
            return q.getResultList();
        } finally {
            entityManager.close();
        }
    }

    @Override
    public List<Survey> findAllByClient(Client client) {
        EntityManager entityManager = getEntityManager();
        try {
            client = entityManager.merge(client);
            CriteriaBuilder cb = entityManager.getCriteriaBuilder();
            CriteriaQuery<Survey> cq = cb.createQuery(Survey.class);
            Root<Survey> root = cq.from(Survey.class);
            cq.select(root);
            cq.where(cb.equal(root.get("client"), client));
            TypedQuery<Survey> q = entityManager.createQuery(cq);
            return q.getResultList();
        } finally {
            entityManager.close();
        }
    }

}

src/main/java/itakademija/java2015/myapp/ui/models/ClientModel.java
package itakademija.java2015.myapp.ui.models;

import itakademija.java2015.myapp.entities.Client;

import java.io.Serializable;

import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ClientModel implements Serializable {

    private static final long serialVersionUID = 5040310448257955354L;

    static final Logger log = LoggerFactory.getLogger(ClientModel.class);

    public void destroy() {
        log.warn("Bean destroyed");
    }

    @Valid
    private Client currentClient;

    public void init() {
        log.warn("Bean created");
        currentClient = new Client();
    }

	public Client getCurrentClient() {
		return currentClient;
	}

	public void setCurrentClient(Client currentClient) {
		this.currentClient = currentClient;
	}


}

src/main/java/itakademija/java2015/myapp/ui/controllers/ClientController.java
package itakademija.java2015.myapp.ui.controllers;

import itakademija.java2015.myapp.entities.Client;
import itakademija.java2015.myapp.entities.Survey;
import itakademija.java2015.myapp.services.ClientService;
import itakademija.java2015.myapp.ui.models.ClientModel;

import java.io.Serializable;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ClientController implements Serializable {

    private static final long serialVersionUID = -8143077418240345336L;

    static final Logger log = LoggerFactory.getLogger(ClientController.class);

    public void init() {
        log.warn("Bean created");
    }

    public void destroy() {
        log.warn("Bean destroyed");
    }

    public static final String NAV_LIST_CLIENTS = "list-clients";
    public static final String NAV_LIST_SURVEYS = "list-surveys";

    private ClientModel clientModel;
    private ClientService clientService;

    public void create() {
        clientModel.setCurrentClient(new Client());
    }

    public String delete(Client client) {
        clientService.delete(client);
        return NAV_LIST_CLIENTS;
    }

    public List<Client> getClientList() {
        return clientService.findAll();
    }

    public List<Survey> findSurveysByClient() {
        return clientModel.getCurrentClient().getSurveys();
    }

    public List<Survey> getFreshSurveyList() {
        Long currentClientId = clientModel.getCurrentClient().getId();
        if (currentClientId == null) return null;
        return clientService.findById(currentClientId).getSurveys();
    }

    public String update(Client client) {
        clientModel.setCurrentClient(client);
        return NAV_LIST_SURVEYS;
    }

    public String save() {
        clientService.save(clientModel.getCurrentClient());
        return NAV_LIST_CLIENTS;
    }

    public String cancel() {
        clientModel.setCurrentClient(new Client());
        return NAV_LIST_CLIENTS;
    }

	public ClientModel getClientModel() {
		return clientModel;
	}

	public void setClientModel(ClientModel clientModel) {
		this.clientModel = clientModel;
	}

	public ClientService getClientService() {
		return clientService;
	}

	public void setClientService(ClientService clientService) {
		this.clientService = clientService;
	}

}

src/main/java/itakademija/java2015/myapp/ui/controllers/SurveyController.java
package itakademija.java2015.myapp.ui.controllers;

import itakademija.java2015.myapp.entities.Survey;
import itakademija.java2015.myapp.services.SurveyService;
import itakademija.java2015.myapp.ui.models.ClientModel;
import itakademija.java2015.myapp.ui.models.SurveyModel;

import java.io.Serializable;
import java.util.Date;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SurveyController implements Serializable {

    private static final long serialVersionUID = -1389684115871062390L;

    static final Logger log = LoggerFactory.getLogger(SurveyController.class);

    public void init() {
        log.warn("Bean created");
    }

    public void destroy() {
        log.warn("Bean destroyed");
    }

    private ClientModel clientModel;
    private SurveyModel surveyModel;
    private SurveyService surveyService;

    public void create() {
        surveyModel.setCurrentSurvey(new Survey());
    }

    public void update(Survey survey) {
        surveyModel.setCurrentSurvey(survey);
    }

    public String save() {
        surveyModel.getCurrentSurvey().setClient(clientModel.getCurrentClient());
        surveyModel.getCurrentSurvey().setSurveyDate(new Date());
        System.out.println("saving date: " + surveyModel.getCurrentSurvey().getSurveyDate());
        surveyService.save(surveyModel.getCurrentSurvey());
        surveyModel.setCurrentSurvey(new Survey());
        return ClientController.NAV_LIST_SURVEYS;
    }

    public String delete(Survey survey) {
        surveyService.delete(survey);
        return ClientController.NAV_LIST_SURVEYS;
    }

    public String cancel() {
        surveyModel.setCurrentSurvey(new Survey());
        return ClientController.NAV_LIST_SURVEYS;
    }

    public SurveyModel getSurveyModel() {
        return surveyModel;
    }
    public void setSurveyModel(SurveyModel surveyModel) {
        this.surveyModel = surveyModel;
    }

    public SurveyService getSurveyService() {
        return surveyService;
    }

    public void setSurveyService(SurveyService surveyService) {
        this.surveyService = surveyService;
    }

	public ClientModel getClientModel() {
		return clientModel;
	}

	public void setClientModel(ClientModel clientModel) {
		this.clientModel = clientModel;
	}

}

src/main/webapp/clients.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

    <ui:define name="content">
        <h:form id="dataTable">
            <p:dataTable value="#{clientController.clientList}" var="client">
                <f:facet name="header">All Clients</f:facet>
                <p:column headerText="Name">
                    <h:outputText value="#{client.name}" />
                </p:column>
                <p:column headerText="Surname">
                    <h:outputText value="#{client.surname}" />
                </p:column>
                <p:column headerText="City">
                    <h:outputText value="#{client.city}" />
                </p:column>
                <p:column headerText="Phone">
                    <h:outputText value="#{client.phone}" />
                </p:column>
                <p:column headerText="">
                    <p:commandButton value="Open"
                        action="#{clientController.update(client)}">
                    </p:commandButton>
                </p:column>
                <p:column headerText="">
                    <p:commandButton value="Delete"
                        action="#{clientController.delete(client)}">
                        <p:confirm header="Confirmation" message="Are you sure?"
                            icon="ui-icon-alert" />
                    </p:commandButton>
                    <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                        <p:commandButton value="Yes" type="button"
                            styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                        <p:commandButton value="No" type="button"
                            styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
                    </p:confirmDialog>
                </p:column>
            </p:dataTable>
        </h:form>
        <p:commandButton action="#{clientController.create}"
            update="updateForm" value="Create client"
            oncomplete="PF('createClient').show();" />
        <p:commandButton action="#{surveyController.create}"
            update="surveyForm" value="Add new survey"
            oncomplete="PF('createSurvey').show();" />
        <p:dialog header="Create Client" widgetVar="createClient"
            modal="true" showEffect="fade" hideEffect="fade"
            resizable="false">
            <h:form id="updateForm">
                <p:outputPanel rendered="#{clientModel.currentClient != null}">
                    <h:panelGrid columns="3" cellpadding="5">
                        <p:outputLabel for="name">Name:</p:outputLabel>
                        <p:inputText id="name"
                            value="#{clientController.clientModel.currentClient.name}"
                            required="true">
                            <f:validateLength minimum="2" maximum="20"/>
                        </p:inputText>
                        <p:message for="name"></p:message>
                        
                        <p:outputLabel for="surname">Surname:</p:outputLabel>
                        <p:inputText id="surname"
                            value="#{clientController.clientModel.currentClient.surname}"
                            required="true">
                            <f:validateLength minimum="2" maximum="20"/>
                        </p:inputText>
                        <p:message for="surname"></p:message>
                        
                        <p:outputLabel for="city">City:</p:outputLabel>
                        <p:inputText id="city"
                            value="#{clientController.clientModel.currentClient.city}">
                            <f:validateLength maximum="20"/>
                        </p:inputText>
                        <p:message for="city"></p:message>

                        <p:outputLabel for="phone">Phone:</p:outputLabel>
                        <p:inputText id="phone"
                            value="#{clientController.clientModel.currentClient.phone}">
                            <f:validateLength maximum="20"/>
                        </p:inputText>
                        <p:message for="phone"></p:message>

                        <p:commandButton value="Save"
                            actionListener="#{clientController.save}"
                            update="updateForm dataTable"
                            oncomplete="if (!args.validationFailed) PF('createClient').hide();">
                        </p:commandButton>
                        <p:commandButton value="Cancel"
                            actionListener="#{clientController.cancel}"
                            update="updateForm dataTable"
                            oncomplete="PF('createClient').hide();" immediate="true">
                        </p:commandButton>
                    </h:panelGrid>
                </p:outputPanel>
            </h:form>
        </p:dialog>
        <p:dialog header="Create Survey" widgetVar="createSurvey"
            modal="true" showEffect="fade" hideEffect="fade"
            resizable="false">
            <h:form id="surveyForm">
                <p:outputPanel rendered="#{surveyModel.currentSurvey != null}">
                    <h:panelGrid columns="3" cellpadding="5">
                        <h:outputLabel for="client" value="Client"></h:outputLabel>
                        <p:selectOneMenu id="client"
                            value="#{clientController.clientModel.currentClient}"
                            converter="#{clientConverter}"
                            required="true">
                            <f:selectItem itemValue="#{null}" itemLabel="Not selected"
                                noSelectionOption="true">
                            </f:selectItem>
                            <f:selectItems
                                value="#{clientController.getClientList()}" 
                                var="listedClient" itemValue="#{listedClient}"
                                itemLabel="#{listedClient.getSurname()}"/>
                        </p:selectOneMenu>
                        <p:message for="client"></p:message>

                        <p:outputLabel for="satisfaction">Satisfaction:</p:outputLabel>
                        <p:inputText id="satisfaction"
                            value="#{surveyController.surveyModel.currentSurvey.satisfaction}">
                            <f:validator binding="#{satisfactionValidator}" />
                        </p:inputText>
                        <p:message for="satisfaction"></p:message>

                        <p:commandButton value="Save"
                            actionListener="#{surveyController.save}"
                            update="surveyForm dataTable"
                            oncomplete="if (!args.validationFailed) PF('createSurvey').hide();">
                        </p:commandButton>
                        <p:commandButton value="Cancel"
                            actionListener="#{surveyController.cancel}"
                            update="surveyForm"
                            oncomplete="PF('createSurvey').hide();" immediate="true">
                        </p:commandButton>
                    </h:panelGrid>
                </p:outputPanel>
            </h:form>
        </p:dialog>
    </ui:define>

    <ui:define name="title">
          All clients
    </ui:define>

</ui:composition>

src/main/webapp/footer.xhtml
<!DOCTYPE html>
<h:html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head></h:head>
<h:body>
    <ui:composition>
        <div id="survey"></div>
    </ui:composition>
</h:body>
</h:html>

src/main/webapp/layout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
    <title>Clients: 
        <ui:insert name="title">
            No title
        </ui:insert>
    </title>
    <h:outputStylesheet name="style.css"></h:outputStylesheet>
</h:head>
<h:body>
    <div id="container">
        <div id="menu">
            <h:form>
                <p:tabMenu>
                    <p:menuitem value="Clients" outcome="list-clients" icon="ui-icon-folder-open">
                    </p:menuitem>
                </p:tabMenu>
            </h:form>
        </div>
        <div id="layout">
            <div id="leftside">
                <ui:insert name="leftside" />
            </div>
            <div id="rightside">
                <ui:insert name="rightside" />
            </div>
        </div>
        <div id="contents">
            <ui:insert name="content" />
        </div>
    </div>
    <div id="footer-container">
        <ui:insert name="footer" />
    </div>
</h:body>
</html>